baseURL = "https://sedlak.biz/"
languageCode = "en-us"
title = "Eddie Webb"

[params]
    firstName = "Daniel"
    lastName = "Sedlak"
    address = "Jablonec nad Nisou, CZ"
    phone = "+420-733576280"
    profileImage = "/img/sedlak_daniel.jpg"
    email = "daniel@sedlak.biz"
    description = "Fullstack developer with love for mobile applications as well as IoT."
    favicon = "images/favicon.ico"

[[params.handles]]
    name = "GitHub"
    link = "https://github.com/wutchzone/"

[[params.handles]]
    name = "Stack Overflow"
    link = "https://stackoverflow.com/users/story/7594900"
    icon = "stack-overflow"

[[params.handles]]
    name = "Twitter"
    link = "https://twitter.com/Daniel_Sedlak98"
